# Generated by Django 2.2.5 on 2020-11-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20201111_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houserule',
            options={'verbose_name_plural': 'House Rule'},
        ),
    ]
