# Generated by Django 2.2.5 on 2020-11-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20201115_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='faciltiy',
            new_name='facilities',
        ),
    ]
