# Generated by Django 2.2.5 on 2020-11-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20201116_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(default=False, help_text='How many people will be staying?'),
        ),
    ]
